### ISSUE TITLE
Leaves blank, quoted lines above and below reply

### ISSUE THREAD

**Issue by koralatov** [Konfekt/mutt-trim#2]
This is great.  It works really well at removing signatures and other junk from quoted replies.  Removing the standard greetings and sign-offs is also a really useful function.

One issue I’ve found is that it leaves blank lines above and below the quoted text.  When it trims off the greeting and sign-off, it doesn’t trim the line immediately below and above, respectively.

I don’t know any Perl, so I don’t know how to add a function to trim these lines.

Here’s an example email showing the issue:

    Hello,

    I’m interested in volunteering for a position on
    the Research Ethics Committee.  Please send me
    an application form, and any other relevant
    documents.

    Many thanks,
    Koralatov

    --
    Koralatov's signature block
    Goes here in the original

And here’s the filtered and trimmed reply with the blank, quoted lines:

    * Koralatov wrote on 2023-05-07 23:32 +0100:
    > 
    > I’m interested in volunteering for a position on 
    > the Research Ethics Committee.  Please send me 
    > an application form, and any other relevant 
    > documents.
    > 

(I hacked together an addition to your script that took care of “Many thanks”.  I’ve [raised a pull](https://github.com/Konfekt/mutt-trim/pull/1).)

**Comment by Konfekt** [comment]
Hello, thanks for the suggestion, whose partial solution took me a while to wrap my head around in [1ee6eb9](https://github.com/Konfekt/mutt-trim/commit/1ee6eb9e7ec44844d58ba716f071ab18be1f49d1).

The initial blank lines are kept as is, as they rather help to read the thread, but the final superfluous ones should now indeed be skipped.
