### ISSUE TITLE
mutt-trim removes blank, quoted lines at end of quote level, not just end of quote block

### ISSUE THREAD

**Issue by koralatov** [Konfekt/mutt-trim#3]
I’m sorry.  It looks like the fix for the [last issue](https://github.com/Konfekt/mutt-trim/issues/2) has introduced a bug.

mutt-trim strips blank lines from a quoted block even when it is _not_ the final line of a quoted block.  It seems to treat the end of a level of quoting the same as the end of the complete quote.

Here’s an example email, to which I’ve replied:
    
    * Other Person wrote on 2021-12-03 12:06 +0000:
    > Please find attached come information about the
    > Committee and becoming a member.
    
    Thanks for providing this -- I've had a good read
    and I'm still very interested.

    > If you have any questions, please don't hesitate
    > to contact us.
   
    I only have one question: are you still carrying
    out meetings remotely?
    
Here’s what happens when I reply to that email:
    
    * Koralatov wrote on 2022-01-27 12:51 +0000:
    > 
    >* Other Person wrote on 2021-12-03 12:06 +0000:
    >> Please find attached come information about the
    >> Committee and becoming a member.
    >
    > Thanks for providing this -- I've had a good read
    > and I'm still very interested.
    >> If you have any questions, please don't hesitate
    >> to contact us.
    >
    > I only have one question: are you still carrying
    > out meetings remotely?
    
mutt-trim has filtered out the blank, quoted line between the sentence ending “very interested” and the one starting “If you have”.

The correct output would leave that blank quoted line intact.

**Comment by Konfekt** [comment]
Well, I misunderstood what you asked for. I thought all empty lines just before the next indentation level to be superfluous; now it only remove those before the lowest one. Please check if it suits your needs.

**Comment by koralatov** [comment]
Thank you for the quick fix; this now works as expected.  Sorry – I probably didn’t explain it clearly in the first issue.

I have noticed one other issue: the script creates blank, quoted lines that have a trailing space on them (“`> `”).  This happens at all levels of quote.

This trailing space means that the resulting emails don’t reflow as expect when sent with `format=flowed` set.  The extra trailing space causes the line to be collapsed by mail clients that treat f=f correctly.  (This is the correct behaviour for `format=flowed`: lines with a trailing space are reflowable depending on the reading client’s preferences.)

I’ve spent a few hours trying to modify the script but haven’t had any success.  I’m reasonably sure that the pattern it needs to match is

    ^(>+)(\s+)$

and that the substitution command would be

    s/\s+$//

but I've had no success with it.

Unfortunately, I haven’t worked out how to add this to the program in a way that works.  My attempts have either broken it entirely, or made absolutely no change to the parsed output.

**Comment by Konfekt** [comment]
Howdy, the digression on the flowed format was interesting, thanks for noting this. I hope to have it settled by the penultimate  commit.

**Comment by Konfekt** [comment]
As you can see, neither `s/\s+$//` nor `chomp()` brought me luck, instead `tr` somehow worked.

**Comment by koralatov** [comment]
Thanks so much for this.  It’s working perfectly now.  I’ve had `mutt-trim` less than a week and it’s so good I can’t believe it’s not default behaviour for `mutt`!

`tr` is a handy tool (and one I use in the process of building my custom headers for mutt), but not one I would have considered using here!
